name: CI

# allow also running manually
on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: ["20.x"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Run ESLint
        run: npm run eslint

      - name: Create archive
        if: github.event_name == 'push'
        run: tar -czf dist.tar.gz dist

      - name: Release on push to branch from fork
        if: github.event_name == 'push' && github.ref != 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:          
          # for a fork PR is the fork itself: owner/fork-name
          repository: ${{ github.repository }} 

          tag_name: ${{ github.ref_name }} # Use the PR branch name as the tag
          name: "Build for commit ${{ github.sha }}"
          files: dist.tar.gz
          overwrite_files: true

      - name: Release on merge to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: dist.tar.gz
          tag_name: main
          overwrite_files: true
